### ISSUE TITLE
A problem about spacy

### ISSUE THREAD

**Issue by hntee** [cedias/NSCUPA-pytorch#1]
Hi, I am trying to run your code, but spacy shows an error.

```
  File "spacy/tokens/doc.pyx", line 438, in __get__ (spacy/tokens/doc.cpp:9707)
    raise ValueError(
ValueError: Sentence boundary detection requires the dependency parse, which requires data to be installed. For more info, see the documentation: 
https://spacy.io/docs/usage
```

After searching, I found that I need to download the spacy corpus first.
`python -m spacy download en`

So I post this issue in case other people come across this situation, and you may update this to the README as well :)

Anyway, thanks again for your code. I am currently reading this paper, your code helps me a lot.

**Comment by cedias** [comment]
Thank you, i'll consider adding a script to test this :+1:
